### ISSUE TITLE
socket:receive() SCHED-ERROR

### ISSUE THREAD

**Issue by cyrusbowman** [SierraWireless/luasched#3]
When I call socket:receive(1024) on a non-blocking socket with a timeout of 1 second `socket:settimeout(1.0,'t')` I receive this error after being connected for a while. I believe it happens more often when there is poor network connection.

SCHED-ERROR: In thread: 0x36b68: /root/aleos/usr/readyagent/lua/sched/timer.lua:152: parameter must be a positive number stack traceback:
    [C]: in function 'assert'
    /root/aleos/usr/readyagent/lua/sched/timer.lua:152: in function 'set'
    /root/aleos/usr/readyagent/lua/sched/init.lua:773: in function 'register'
    /root/aleos/usr/readyagent/lua/sched/init.lua:877: in function 'wait'
    /root/aleos/usr/readyagent/lua/sched/fd.lua:100: in function </root/aleos/usr/readyagent/lua/sched/fd.lua:92>
    (tail call): ?
    /root/aleos/usr/readyagent/lua/socket/platform.lua:144: in function 'receive'
    main.lua:368: in function main.lua:149

**Comment by cbugot** [comment]
Hi Cyrus,
From the logs above it seems that you are running your code on an Airlink gateway running ALEOS application Framework. Did you try to contact the Sierra support to get support on the actual gateway (you'll need that to have the bugfix released in a new ALEOS firmware)

**Comment by cyrusbowman** [comment]
Cuero,

Thanks for the quick response. Sierra support is a pain to get ahold of, you have to go through the reseller of the device. I ended up switching to 'block' timeout mode `socket:settimeout(1.0, 'b')` which works without a problem.

**Comment by cbugot-swi** [comment]
Hi Cyrus,
This bug is being fixed into AAF, and the fix will be available in ALEOS 4.6.0.
I also pushed the fix on this repository, if anyone is interested.
So regular 'total' timeout can be used again :)
